#Stage 1: Build
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build
RUN ls -la dist  # optional: debug

#Stage 2: Production
FROM node:18-slim

WORKDIR /app

COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/medusa-config.js ./ 

EXPOSE 9000

CMD ["npm", "run", "start"]

